name: refseg
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - cpuonly
  - numpy
  - opencv
  - pillow
  - pyyaml
  - tqdm
  - matplotlib
  - pip
  - pip:
      - timm
      - transformers
      - segment-anything

